/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package AdminPack;

import java.io.IOException;
import java.util.List;
import java.util.Vector;

import twitter4j.*;

import twitter4j.auth.AccessToken;

public class NamexTweet {

    private final static String CONSUMER_KEY = "SWKbdiUWXY7mjpm0kba9UXrjI";
    private final static String CONSUMER_KEY_SECRET
            = "vUz5eDPjWSDu6OpA8Z5QltLSGkBRiHe5VIViHC7cfoL30AtqBQ";
    public static boolean status = true;

    public void start() throws TwitterException, IOException {

        fetch_tweet();
    }

    public static boolean fetch_tweet() {
        //  MainForm.tweet = new Vector<String>();
        try {
            status=true;
            Twitter twitter = new TwitterFactory().getInstance();
            twitter.setOAuthConsumer(CONSUMER_KEY, CONSUMER_KEY_SECRET);
            // here's the difference

            String accessToken = "2890648028-Nhdku2emUwGBETWwDIZQ1LV6hDYl05RcMgmmLa1";

            String accessTokenSecret = "3jLkW1V3ZkZQVP6jq9U2IL9zan8VdRzyfGhTeoVebOY7k";

            AccessToken oathAccessToken = new AccessToken(accessToken,
                    accessTokenSecret);

            twitter.setOAuthAccessToken(oathAccessToken);

            twitter.updateStatus(SingleSentense.TweetData);

        } catch (Exception e) {
            System.out.println("Error : " + e);
            e.printStackTrace();
            status = false;
        }
        return status;
    }

//    public static String parse_String(String input) {
//        String return_output = "";
//        int len = input.length();
//        for (int i = 0; i < len; i++) {
//            Character ss = input.charAt(i);
//            int ascc = (int) ss;
//            if (ascc == 32) {
//                return_output += " ";
//            } else {
//                if ((ascc >= 64 && ascc <= 90) || (ascc >= 97 && ascc <= 122)) {
//                    return_output += ss;
//                }
//            }
//        }
//        return return_output;
//    }
    private String getSavedAccessTokenSecret() {

        // consider this is method to get your previously saved Access Token
        // Secret
        return "Enter Secret AccessToken generated by NamexTweet";

    }

    private String getSavedAccessToken() {

        // consider this is method to get your previously saved Access Token
        return "Enter AccessToken generated by NamexTweet";

    }

//    public static void main(String[] args) throws Exception {
//
//        new NamexTweet().start();
//
//    }
}
